# Generated by Django 6.0.4 on 2026-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_dish_cartitem_order_orderitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='composition',
            field=models.TextField(blank=True, help_text='Перечислите ингредиенты', verbose_name='Состав блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='nutrition',
            field=models.CharField(blank=True, help_text='Калории, белки, жиры, углеводы', max_length=100, verbose_name='КБЖУ'),
        ),
    ]
