# Generated by Django 6.0.4 on 2026-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dish_composition_dish_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='nutrition',
            field=models.CharField(blank=True, max_length=100, verbose_name='КБЖУ'),
        ),
    ]
