# Generated by Django 6.0.4 on 2026-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dish_composition_alter_dish_nutrition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'is_available'], name='main_dish_categor_6169c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['name'], name='main_dish_name_e8a584_idx'),
        ),
    ]
