# Generated by Django 6.0.4 on 2026-06-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dish_main_dish_categor_6169c7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='slug',
        ),
    ]
