# Generated by Django 6.0.4 on 2026-06-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_category_slug_remove_dish_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
    ]
