# Generated by Django 6.0.4 on 2026-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr', 'QR-код'), ('cash', 'Наличными')], default='qr', max_length=10),
        ),
    ]
